version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  vault_auth:
    docker:
      - image: vault:1.3.3
    steps:
      - checkout
      - run:
          command: |
            echo $VAULT_ROLE_ID > vault/role-id
            echo $VAULT_SECRET_ID	> vault/secret-id
            vault agent -config=vault/agent.hcl
      - persist_to_workspace:
          root: /project/vault
            # Must be relative path from root
          paths:
            - dockerhub
  kubeconfig:
    docker:
      - image: joatmon08/circleci-gcp-agent:287.0-1.14.72
    steps:
      - run:
          name: Authenticate to Vault
          command: echo "vault"
      - run:
          name: Authenticate to GCP
          command: |
            gcloud auth activate-service-account --key-file=/tmp/service-account
            gcloud config set project $(cat /tmp/gcp-project)
            gcloud container clusters get-credentials $(cat /tmp/kubernetes-cluster) --zone $(cat /tmp/kubernetes-cluster-zone)
      - persist_to_workspace:
          root: /root/.kube
          paths:
            - config

workflows:
  build_test:
    jobs:
      - run_tests
      - vault_auth
